# Generated by Django 4.1.1 on 2022-09-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
