# Generated by Django 4.1.1 on 2022-09-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_book_busy_alter_book_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='end_time',
        ),
    ]
