# Generated by Django 4.1.1 on 2022-09-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter drug name', max_length=1500, verbose_name='Drug')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='drugs-images')),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
