# Generated by Django 4.1.1 on 2022-09-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='price',
            field=models.CharField(default='15000', max_length=6000000),
        ),
    ]
