# Generated by Django 4.1.1 on 2022-09-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Enter doctor fullname', max_length=600, verbose_name='Doctor name')),
                ('image', models.ImageField(help_text='Upload doctor image', upload_to='doctor-image', verbose_name='Doctor image')),
                ('profession', models.CharField(help_text='Enter doctor profession', max_length=600, verbose_name='Doctor profession')),
                ('phone', models.CharField(help_text='Enter phone number', max_length=600, verbose_name='Doctor phone number')),
                ('address', models.CharField(help_text='Enter doctor address', max_length=600, verbose_name='Doctor adress')),
                ('job', models.CharField(help_text='Enter doctor position', max_length=800, verbose_name='Doctor position')),
            ],
        ),
    ]
